name: Dockerized Echo Chamber API CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0

    - name: Set up Docker
      uses: docker/setup-qemu-action@v3.0.0

    - name: Build Docker image
      run: docker build -t echo-chamber:latest -f Dockerfile .

    - name: AWS ECR Login
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }} --profile ecr-user
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }} --profile ecr-user
        aws configure set region ${{ secrets.AWS_REGION }} --profile ecr-user
        aws ecr get-login-password --profile ecr-user | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Tag Docker image
      run: |
        docker tag echo-chamber:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/echo-chamber:latest
        docker tag echo-chamber:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/echo-chamber:$(date +%T)

    - name: Push Docker image to AWS ECR
      run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/echo-chamber:latest
